/run/initialize 
/vis/open OGL 
/vis/drawVolume 

/vis/scene/add/trajectories smooth 
/vis/modeling/trajectories/create/drawByCharge 
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true 
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2 

/vis/scene/add/axes 0 0 0 1 m 

/vis/viewer/set/style surface 
/vis/viewer/set/autoRefresh true 
/vis/viewer/flush /tracking/storeTrajectory 1 

/vis/scene/endOfEventAction accumulate 
/run/beamOn 1000
